import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header"
import "./globals.css";
import StateContextProvider from "@/context/context.jsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContextProvider>
        <div className="flex-1 max-sm:w-full max-w-[1280px] mx-auto sm:pr-5  flex flex-col p-4">
          <Header />
          {children}
          {/* <footer className='text-white '>
            <div className="container flex flex-col items-center justify-between gap-4 py-10 md:h-24 md:flex-row md:py-0">
              <div className="flex flex-col items-center gap-4 px-8 md:flex-row md:gap-2 md:px-0">
                <Icon imgUrl={'assets/logo.svg'} styles="w-[52px] h-[52px] bg-[#2c2f32]" />
                <p className="text-center text-sm leading-loose md:text-left">
                  built_by {" "}
                  <a
                    href={siteConfig.links.twitter}
                    target="_blank"
                    rel="noreferrer"
                    className="font-medium underline underline-offset-4"
                  >
                    Rozales
                  </a>

                  . The source code is available on{" "}
                  <a
                    href={siteConfig.links.github}
                    target="_blank"
                    rel="noreferrer"
                    className="font-medium underline underline-offset-4"
                  >
                    GitHub
                  </a>
                  .
                </p>
              </div>
            </div>
          </footer> */}
        </div>
        </StateContextProvider>
      </body>
    </html >
  );
}
